version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/banking_analysis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WISE_API_KEY=${WISE_API_KEY}
      - REVOLUT_API_KEY=${REVOLUT_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - banking-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=banking_analysis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  postgres_data: 